name: Publish Sirji VS Code Extension

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Change directory to extension
        run: cd sirji/vscode-extension

      - name: Install VSCE
        run: npm install -g vsce

      - name: Install dependencies
        run: npm install
      
      - name: Compile and Copy Files
        run: npm run vscode:prepublish

      - name: Prepack Extension
        run: npm run prepack

      - name: Package Extension
        run: npm run package

      - name: Publish Extension
        run: npm run publish -- -p ${{ secrets.VS_MARKETPLACE_PAT }}
        env:
          VS_MARKETPLACE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
