name: Publish Sirji VS Code Extension

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install VSCE
        run: npm install -g vsce

      - name: Change directory and run all scripts
        run: |
          echo "Changing directory to sirji/vscode-extension"
          cd sirji/vscode-extension

          echo "Installing dependencies"
          npm install
          echo "Running prepublishing steps"
          npm run vscode:prepublish

          echo "Running pre-pack steps"
          npm run prepack

          echo "Packaging extension"
          npm run package

        shell: bash
      
      # Uncomment the following to enable publishing
      # - name: Publish Extension
      #   run: |
      #     cd sirji/vscode-extension
      #     npm run publish -- -p ${{ secrets.VS_MARKETPLACE_PAT }}
      #   env:
      #     VS_MARKETPLACE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
      #   shell: bash
