name: Publish Python Package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to release (agents, messages, tools)'
        required: true
        default: 'agents'
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd ${{ github.event.inputs.package }}
          python setup.py sdist bdist_wheel
          twine upload dist/*
